import numpy as np
import itertools

ON_RAMP_STARTS = [0, 260]
OFF_RAMP_STARTS = [150, 410]

RUNWAY_LENGTH = 5
CONVERGE_LENGTH = 20
MERGE_LENGTH = 60
BARRIER_LENGTH = 5

RAMP_LENGTH = RUNWAY_LENGTH + CONVERGE_LENGTH + MERGE_LENGTH

MERGE_SECTION_LENGTH = MERGE_LENGTH + BARRIER_LENGTH

ON_RAMP_MERGE_STARTS = np.array(ON_RAMP_STARTS) + RUNWAY_LENGTH + CONVERGE_LENGTH

MERGEABLE_SECTION_STARTS = np.array(list(itertools.chain(*zip(ON_RAMP_MERGE_STARTS, OFF_RAMP_STARTS))))

NUM_LANES = 8
NUM_UPSTREAM = NUM_LANES // 2

RIGHT_LANE_INDEX = NUM_LANES
LEFT_LANE_INDEX = 1

LANE_WIDTH = 4.0

RAMP_WIDTH = 2 * LANE_WIDTH
Y_UPSTREAM_RAMP_START = RAMP_WIDTH
Y_ROAD_START = Y_UPSTREAM_RAMP_START + RAMP_WIDTH
ROAD_WIDTH = (NUM_LANES - 1) * LANE_WIDTH
Y_DOWNSTREAM_RAMP_START = Y_ROAD_START + ROAD_WIDTH + RAMP_WIDTH

WEST_NODE = 'west'
EAST_NODE = 'east'

HIGHWAY_SPEED_LIMIT: float = 100.0 / 3.6
RAMP_SPEED_LIMIT: float = 80.0 / 3.6