# Road
ROAD_LENGTH = 500.0

LANE_WIDTH = 4.0

NUM_LANES = 8

SCREEN_WIDTH = 1680
SCREEN_HEIGHT = 1050
SCALING = 3.36

DISPLAY_METRICS = False

ADD_UPSTREAM_ENTRY_RAMPS = True
ADD_DOWNSTREAM_ENTRY_RAMPS = True
ADD_UPSTREAM_EXIT_RAMPS = True
ADD_DOWNSTREAM_EXIT_RAMPS = True
