# Road
ROAD_LENGTH = 500.0

LANE_WIDTH = 4.0

NUM_LANES = 8

HIGHWAY_SPEED_LIMIT = 100 / 3.6
RAMP_SPEED_LIMIT = 60 / 3.6

DISPLAY_METRICS = False

ADD_UPSTREAM_ENTRY_RAMPS = True
ADD_DOWNSTREAM_ENTRY_RAMPS = True
ADD_UPSTREAM_EXIT_RAMPS = True
ADD_DOWNSTREAM_EXIT_RAMPS = True

WEST_NODE = 'west'
EAST_NODE = 'east'

DETECTION_POINTS = [10, ROAD_LENGTH//4, ROAD_LENGTH//2, ROAD_LENGTH*(3//4), ROAD_LENGTH-10]